/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:283cdf4f-6dd2-4b2a-8490-25c077a9cdd1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Mvyk7pn28",
    "aws_user_pools_web_client_id": "19qm7b60cts49bj3co9glhfo31",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://5usf3zknxngv3jakblmi7b6zzi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
